version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - build-css
  
  build-css:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/app
    command: npm run build-css
  
  mock-server:
    image: mockserver/mockserver:5.15.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - "./mock-server/config:/config"