export const getFundsStorage = () => [
  {
    ticker: 'AAGR11',
    name: 'Asset Bank Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'AZUMI DTVM',
  },
  {
    ticker: 'AAZQ11',
    name: 'AZ Quest Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'ABCP11',
    name: 'Grand Plaza Shopping',
    serie: 'Shopping/Varejo',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'AFHI11',
    name: 'AF Invest CRI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'AGRX11',
    name: 'Exes Araguaia Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'AIEC11',
    name: 'Autonomy Edifícios Corporativos',
    serie: 'Lajes Comerciais',
    adminitrator: 'MAF',
  },
  {
    ticker: 'ALMI11',
    name: 'Torre Almirante',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ALZC11',
    name: 'Alianza Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ALZM11',
    name: 'Alianza Multiestratégia',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ALZR11',
    name: 'Alianza Trust Renda Imobiliária',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'AMAZ11',
    name: 'Bloxs Amazon Green Legacy',
    serie: 'Agronegócio',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'ANCR11B',
    name: 'Ancar IC',
    serie: 'Shopping/Varejo',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'APTO11',
    name: 'Navi Residencial',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'APXM11',
    name: 'Apex Malls',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'AQLL11',
    name: 'Áquilla',
    serie: 'Incorporação',
    adminitrator: 'RJI',
  },
  {
    ticker: 'ARFI11B',
    name: 'AQ3 Renda',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'ÍNDIGO INVESTIMENTOS',
  },
  {
    ticker: 'AROA11',
    name: 'Aroeira 333 Renda Logística',
    serie: 'Outros',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'ARRI11',
    name: 'Átrio Reit Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'ARXD11',
    name: 'ARX Dover Recebíveis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'ASMT11',
    name: 'ASA Metropolis',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ASRF11',
    name: 'Asa Retrofits I',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ATCR11',
    name: 'HAZ FII',
    serie: 'Hoteis',
    adminitrator: 'RJI',
  },
  {
    ticker: 'ATSA11',
    name: 'Hedge Atrium Shopping Santo André',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'ATWN11',
    name: 'Airport Town',
    serie: 'Incorporação',
    adminitrator: 'REAG',
  },
  {
    ticker: 'AURB11',
    name: 'Alianza Urban Hub Renda',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BARI11',
    name: 'Barigui Rendimentos',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'BBFI11B',
    name: 'BB Progressivo',
    serie: 'Agencias Bancárias',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BBFO11',
    name: 'BB Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BB GESTAO DE RECURSOS',
  },
  {
    ticker: 'BBGO11',
    name: 'BB Crédito Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BB GESTAO DE RECURSOS',
  },
  {
    ticker: 'BBIM11',
    name: 'BB Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BB GESTAO DE RECURSOS',
  },
  {
    ticker: 'BBPO11',
    name: 'BB Progressivo II',
    serie: 'Agencias Bancárias',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'BBRC11',
    name: 'BB Renda Corporativa',
    serie: 'Agencias Bancárias',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'BCFF11',
    name: 'BTG Pactual Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BCIA11',
    name: 'Bradesco Carteira Imobiliária Ativa',
    serie: 'Fundo de Fundos',
    adminitrator: 'BANCO BRADESCO',
  },
  {
    ticker: 'BCRI11',
    name: 'Banestes Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BDIF11',
    name: 'BTG Pactual Dívida FI-Infra',
    serie: 'N/D',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BICE11',
    name: 'Brio Crédito Estruturado',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BICR11',
    name: 'Inter Títulos Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'BIDB11',
    name: 'Inter FI-Infra',
    serie: 'N/D',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'BIME11',
    name: 'Brio Multiestratégia',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BIPD11',
    name: 'Brio Real Estate IV',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BJRC11',
    name: 'JS Real Estate Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO J. SAFRA',
  },
  {
    ticker: 'BLCA11',
    name: 'Catuaí VBI Triple A',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BLCP11',
    name: 'Bluecap Renda Logística',
    serie: 'Logisticos',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BLMC11',
    name: 'VBI Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BLMG11',
    name: 'BlueMacaw Logística',
    serie: 'Logisticos',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'BLMO11',
    name: 'VBI Office Fund II',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BLMR11',
    name: 'VBI Renda + FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BLUR11',
    name: 'Blue Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'BMII11',
    name: 'Brasílio Machado',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'BMLC11',
    name: 'BM Brascan Lajes Corporativas',
    serie: 'Lajes Comerciais',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BNFS11',
    name: 'Banrisul Novas Fronteiras',
    serie: 'Agencias Bancárias',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'BODB11',
    name: 'Bocaina FI-Infra',
    serie: 'N/D',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BPFF11',
    name: 'Brasil Plural Absoluto Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'BPLC11',
    name: 'Basílica Partners LED Corporate',
    serie: 'Híbrido',
    adminitrator: 'FRAM Capital',
  },
  {
    ticker: 'BPMA11',
    name: 'Brio Prime Malls',
    serie: 'Shopping/Varejo',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BPML11',
    name: 'BTG Pactual Shoppings',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BPRP11',
    name: 'BRLPROP',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BRCO11',
    name: 'Bresco Logística',
    serie: 'Logisticos',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'BRCR11',
    name: 'BTG Pactual Corporate Office Fund',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BREV11',
    name: 'Brazil Real Estate Victory Fund I',
    serie: 'Lajes Comerciais',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'BRHT11B',
    name: 'BR Hoteis',
    serie: 'Hoteis',
    adminitrator: 'RJI',
  },
  {
    ticker: 'BRIM11',
    name: 'Brio Real Estate II',
    serie: 'Incorporação Residencial',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BRIP11',
    name: 'Brio Real Estate III',
    serie: 'Incorporação Residencial',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BRIX11',
    name: 'Brix FII',
    serie: 'Incorporação',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BRLA11',
    name: 'BRL Prop II',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BROF11',
    name: 'BRPR Corporate Offices',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BRSE11',
    name: 'BR7 Senado',
    serie: 'Outros',
    adminitrator: 'FRAM Capital',
  },
  {
    ticker: 'BTAL11',
    name: 'Btg Pactual Agro Logística',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BTCI11',
    name: 'BTG Pactual Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BTCR11',
    name: 'BTG Pactual Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BTLG11',
    name: 'BTG Pactual Logística',
    serie: 'Logisticos',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'BTRA11',
    name: 'BTG Pactual Terras Agrícolas',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'BTSG11',
    name: 'BTSP I',
    serie: 'Incorporação',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'BTSI11',
    name: 'BTSP II',
    serie: 'Híbrido',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'BTWR11',
    name: 'BTowers',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'BVAR11',
    name: 'Brasil Varejo',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'BZEL11',
    name: 'Barzel CD1',
    serie: 'Híbrido',
    adminitrator: 'BANCO OURINVEST S.A.',
  },
  {
    ticker: 'BZLI11',
    name: 'Brazil Realty',
    serie: 'Híbrido',
    adminitrator: 'ÍNDIGO INVESTIMENTOS',
  },
  {
    ticker: 'CACR11',
    name: 'Cartesia Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'CARE11',
    name: 'Brazilian GraveyardDeath Care',
    serie: 'Outros',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'CBOP11',
    name: 'Castello Branco Office Park',
    serie: 'Lajes Comerciais',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'CCLB11',
    name: 'Central Leblon FII',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'CCME11',
    name: 'Canuma Capital Multiestratégia',
    serie: 'Outros',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CCRF11',
    name: 'RBR CRI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CDII11',
    name: 'Sparta Infra CDI',
    serie: 'N/D',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CEOC11',
    name: 'CEO Cyrela Commercial Properties',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CFHI11',
    name: 'CF2 FII',
    serie: 'Lajes Comerciais',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'CFII11',
    name: 'CF3 FII',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'CIXR11',
    name: 'CIX Rendimento',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'CJCT11',
    name: 'Cidade Jardim Continental Tower',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'CJFI11',
    name: 'CJ FII',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CNES11',
    name: 'Cenesp',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'COPP11',
    name: 'Corporate Office Properties',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CPFF11',
    name: 'Capitânia REIT FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CPFO11',
    name: 'Capitânia REIT FOF II',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CPSH11',
    name: 'Shoppings AAA',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CPTI11',
    name: 'Capitânia FI-Infra',
    serie: 'N/D',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'CPTR11',
    name: 'Capitânia Agro Strategies Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CPTS11',
    name: 'Capitânia Securities II',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CRAA11',
    name: 'Sparta Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CRFF11',
    name: 'Caixa Rio Bravo Fundo de Fundos II',
    serie: 'Fundo de Fundos',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'CSMC11',
    name: 'Cosmic',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'CTXT11',
    name: 'Centro Têxtil Internacional',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'CVBI11',
    name: 'VBI CRI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'CVPR11',
    name: 'CVPAR',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'CXAG11',
    name: 'Caixa Agencias',
    serie: 'Agencias Bancárias',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'CXCE11B',
    name: 'Caixa Cedae',
    serie: 'Lajes Comerciais',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'CXCI11',
    name: 'Caixa Carteira Imobiliária',
    serie: 'Fundo de Fundos',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'CXCO11',
    name: 'Caixa Imóveis Corporativos',
    serie: 'Lajes Comerciais',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'CXRI11',
    name: 'Caixa Rio Bravo Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'CXTL11',
    name: 'Caixa Seq Logística Renda',
    serie: 'Logisticos',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'CYCR11',
    name: 'Cyrela Crédito',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'CYLD11',
    name: 'Cyrela Desenvolvimento Logístico',
    serie: 'Logisticos',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'DAMT11B',
    name: 'Diamante',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'DCRA11',
    name: 'Devant Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'DEVA11',
    name: 'Devant Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'DLMT11',
    name: 'Del Monte Ajax',
    serie: 'Lajes Comerciais',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'DMAC11',
    name: 'MAC FII',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'DOVL11B',
    name: 'Dovel',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'DPRO11',
    name: 'Devant Properties',
    serie: 'Logisticos',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'DRIT11B',
    name: 'Multigestão Renda Comercial',
    serie: 'Lajes Comerciais',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'DVFF11',
    name: 'Devant Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'EDFO11B',
    name: 'Edifício Ourinvest',
    serie: 'Lajes Comerciais',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'EDGA11',
    name: 'Edifício Galeria',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'EGAF11',
    name: 'Ecoagro I Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'EGYR11',
    name: 'Energy Resort',
    serie: 'Incorporação Residencial',
    adminitrator: 'REAG',
  },
  {
    ticker: 'ELDO11B',
    name: 'Eldorado',
    serie: 'Shopping/Varejo',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'EQIR11',
    name: 'EQI Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ERCR11',
    name: 'Estoque Residencial e Comercial Rio de Janeiro',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'ERPA11',
    name: 'Europa 105',
    serie: 'Lajes Comerciais',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'ESTQ11',
    name: 'Polo Estoque II',
    serie: 'Lajes Comerciais',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'EURO11',
    name: 'Europar',
    serie: 'Logisticos',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'EVBI11',
    name: 'VBI Consumo Essencial',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'EXES11',
    name: 'Exes',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FAED11',
    name: 'Anhanguera Educacional',
    serie: 'Educacional',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FAGL11',
    name: 'Fator Renda Galpão',
    serie: 'N/D',
    adminitrator: 'BANCO FATOR',
  },
  {
    ticker: 'FAMB11B',
    name: 'Edifício Almirante Barroso',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FARU11',
    name: 'Fator Renda Urbana',
    serie: 'N/D',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'FATN11',
    name: 'Athena I',
    serie: 'Híbrido',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'FCAS11',
    name: 'Edifício Castelo',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FCFL11',
    name: 'Campus Faria Lima',
    serie: 'Educacional',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FGAA11',
    name: 'FG/Agro Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'FGPM11',
    name: 'Grand Plaza Mall',
    serie: 'Shopping/Varejo',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'FIGS11',
    name: 'General Shopping Ativo e Renda',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'FIIB11',
    name: 'Industrial do Brasil',
    serie: 'Logisticos',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'FIIP11B',
    name: 'RB Capital Renda I',
    serie: 'Híbrido',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'FINF11',
    name: 'Infra Real Estate',
    serie: 'Logisticos',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'FISC11',
    name: 'SC 401',
    serie: 'Lajes Comerciais',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'FISD11',
    name: 'São Domingos',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'RJI',
  },
  {
    ticker: 'FIVN11',
    name: 'Vida Nova',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'FLCR11',
    name: 'Faria Lima Capital Recebíveis Imobiliários I',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'FLEM11',
    name: '051 Agro Fazendas II',
    serie: 'Agronegócio',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'FLMA11',
    name: 'Continental Square Faria Lima',
    serie: 'Lajes Comerciais',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'FLRP11',
    name: 'Hedge Floripa Shopping',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'FMOF11',
    name: 'Memorial Office',
    serie: 'Lajes Comerciais',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'FOFT11',
    name: 'Hedge TOP FOFII 2',
    serie: 'Fundo de Fundos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'FPAB11',
    name: 'Projeto Água Branca',
    serie: 'Lajes Comerciais',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'FPNG11',
    name: 'Pedra Negra Renda Imobiliária',
    serie: 'Lajes Comerciais',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'FRHY11',
    name: 'Fronteira Multi',
    serie: 'N/D',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'FTCE11B',
    name: 'Opportunity',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'FTMJ11',
    name: 'TMJ FII',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'GRADUAL',
  },
  {
    ticker: 'FVBI11',
    name: 'VBI FL 4440',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'FVPQ11',
    name: 'Via Parque',
    serie: 'Shopping/Varejo',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'FZDA11',
    name: '051 Agro Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'FZDB11',
    name: '051 Agro Fazendas III',
    serie: 'Agronegócio',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'GALG11',
    name: 'Guardian Logística',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'GAME11',
    name: 'Guardian Multiestratégia Imobiliária I',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'GCFF11',
    name: 'Galapagos Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'GCOI11',
    name: 'Galapagos Special Oportunities',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'GCRA11',
    name: 'Galapagos Recebíveis do Agronegócio Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'GCRI11',
    name: 'Galapagos Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'GESE11B',
    name: 'General Severiano',
    serie: 'Outros',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'GGRC11',
    name: 'GGR Covepi',
    serie: 'Logisticos',
    adminitrator: 'CM CAPITAL MARKETS',
  },
  {
    ticker: 'GLOG11',
    name: 'Genial Logística',
    serie: 'Logisticos',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'GRLV11',
    name: 'GR Louveira',
    serie: 'Logisticos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'GRWA11',
    name: 'Greenwich Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'GSFI11',
    name: 'General Shopping e Outlets',
    serie: 'Shopping/Varejo',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'GTLG11',
    name: 'Gtis Brazil Logistics',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'GTWR11',
    name: 'Green Towers',
    serie: 'Lajes Comerciais',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'GURB11',
    name: 'Genial Renda Urbana',
    serie: 'Híbrido',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'GVBI11',
    name: 'VBI GreenPower',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'GWIC11',
    name: 'GWI Condomínios Logísticos',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'GZIT11',
    name: 'Gazit Malls',
    serie: 'N/D',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'HAAA11',
    name: 'Hedge AAA',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HABT11',
    name: 'Habitat Recebíveis Pulverizados',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HBCR11',
    name: 'HBC Renda Urbana',
    serie: 'Lajes Comerciais',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'HBRH11',
    name: 'Multi Renda Urbana',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'HBTT11',
    name: 'Habitat I',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HCHG11',
    name: 'Hectare Recebíveis High Grade',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HCRI11',
    name: 'Hospital da Criança',
    serie: 'Hospital',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'HCST11',
    name: 'Hectare Desenvolvimento Student Housing',
    serie: 'Residencial',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HCTR11',
    name: 'Hectare CE',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HDEL11',
    name: 'Hedge Desenvolvimento Logístico',
    serie: 'Logisticos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HDOF11',
    name: 'Hedge Paladin Design Offices',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HFOF11',
    name: 'Hedge TOP FOFII 3',
    serie: 'Fundo de Fundos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HGAG11',
    name: 'High Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HGBS11',
    name: 'Hedge Brasil Shopping',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HGCR11',
    name: 'CSHG Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGFF11',
    name: 'CSHG Imobiliário FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGIC11',
    name: 'HGI Créditos Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'HGLG11',
    name: 'CSHG Logística',
    serie: 'Logisticos',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGPO11',
    name: 'CSHG Prime Offices',
    serie: 'Lajes Comerciais',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGRE11',
    name: 'CSHG Real Estate',
    serie: 'Lajes Comerciais',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGRS11',
    name: 'CSHG Residencial',
    serie: 'Residencial',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HGRU11',
    name: 'CSHG Renda Urbana',
    serie: 'Híbrido',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'HILG11',
    name: 'Hire Log I',
    serie: 'Outros',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'HLOG11',
    name: 'Hedge Logística',
    serie: 'Logisticos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HMOC11',
    name: 'Hedge Shopping Praça da Moça',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HOFC11',
    name: 'Hedge Office Income',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HOSI11',
    name: 'Housi',
    serie: 'Residencial',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'HPDP11',
    name: 'Hedge Shopping Parque Dom Pedro',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HRDF11',
    name: 'Hedge Realty Development',
    serie: 'Incorporação',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HREC11',
    name: 'Hedge Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'HSAF11',
    name: 'HSI Ativos Financeiros',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'HSLG11',
    name: 'HSI Logística',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'HSML11',
    name: 'HSI Malls',
    serie: 'Shopping/Varejo',
    adminitrator: 'SANTANDER CACEIS',
  },
  {
    ticker: 'HSRE11',
    name: 'HSI Renda Imobiliária',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'HTMX11',
    name: 'Hotel Maxinvest',
    serie: 'Hoteis',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'HUCG11',
    name: 'Hospital Unimed Campina Grande',
    serie: 'Hospital',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'HUSC11',
    name: 'Hospital Unimed Sul Capixaba',
    serie: 'Hospital',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'HUSI11',
    name: 'HUSI',
    serie: 'Hospital',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'IAAG11',
    name: 'Inter Amerra',
    serie: 'Agronegócio',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'IAGR11',
    name: 'SFI Investimentos do Agronegócio Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'WARREN',
  },
  {
    ticker: 'IBCR11',
    name: 'CRI Integral Brei',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'IBFF11',
    name: 'FOF Integral Brei',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'IDFI11',
    name: 'Unidades Autônomas',
    serie: 'Híbrido',
    adminitrator: 'ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.',
  },
  {
    ticker: 'IDGR11',
    name: 'Unidades Autônomas II',
    serie: 'Híbrido',
    adminitrator: 'ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.',
  },
  {
    ticker: 'IFIX',
    name: 'IFIX Índice de Fundos Imobiliários',
    serie: 'N/D',
    adminitrator: 'N/D',
  },
  {
    ticker: 'IFRA11',
    name: 'Itaú FIC FI-Infra',
    serie: 'N/D',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'IMOF11',
    name: 'Propp I',
    serie: 'Híbrido',
    adminitrator: 'BEM DTVM',
  },
  {
    ticker: 'IRDM11',
    name: 'Iridium Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'IRIM11',
    name: 'Iridium',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'ITIP11',
    name: 'Inter Teva Índice de Papel',
    serie: 'Fundo de Fundos',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'ITIT11',
    name: 'Inter Teva Índice de Tijolo',
    serie: 'Fundo de Fundos',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'JASC11',
    name: 'Jasc Renda Varejo FII',
    serie: 'Outros',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'JBFO11',
    name: 'JBFO FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BEM DTVM',
  },
  {
    ticker: 'JCDA11',
    name: 'Jacarandá I',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'JCDB11',
    name: 'Jacarandá II',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'JFLL11',
    name: 'JFL Living',
    serie: 'Residencial',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'JGPX11',
    name: 'JGP Crédito Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'JPPA11',
    name: 'JPP Capital Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'FINAXIS CORRETORA',
  },
  {
    ticker: 'JPPC11',
    name: 'JPP Capital',
    serie: 'Incorporação',
    adminitrator: 'BANCO FINAXIS',
  },
  {
    ticker: 'JRDM11',
    name: 'Shopping Jardim Sul',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'JSAF11',
    name: 'JS Ativos Financeiros',
    serie: 'Fundo de Fundos',
    adminitrator: 'BANCO J. SAFRA',
  },
  {
    ticker: 'JSIM11',
    name: 'JS Real Estate Renda Imobiliária',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO J. SAFRA',
  },
  {
    ticker: 'JSRE11',
    name: 'JS Real Estate Multigestão',
    serie: 'Lajes Comerciais',
    adminitrator: 'BANCO J. SAFRA',
  },
  {
    ticker: 'JTPR11',
    name: 'JT PREV Desenvolvimento Habitacional',
    serie: 'Incorporação Residencial',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'JURO11',
    name: 'Sparta FI-Infra',
    serie: 'N/D',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'KCRE11',
    name: 'Kinea Creditas',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KDIF11',
    name: 'Kinea FI-Infra',
    serie: 'N/D',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KEVE11',
    name: 'Even II',
    serie: 'Incorporação Residencial',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KFOF11',
    name: 'Kinea Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KINP11',
    name: 'Even Permuta Kinea',
    serie: 'Incorporação Residencial',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KISU11',
    name: 'Kilima FoF Suno 30',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'KIVO11',
    name: 'Kilima Volkano Recebíveis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'KNCA11',
    name: 'Kinea Crédito Agro Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNCR11',
    name: 'Kinea Rendimentos Imobiliários FII',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNHF11',
    name: 'Kinea Hedge Fund',
    serie: 'Híbrido',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNHY11',
    name: 'Kinea High Yield CRI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNIP11',
    name: 'Kinea Índices de Preços',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNPR11',
    name: 'Kinea Premium Properties FII',
    serie: 'Fundo de Fundos',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNRE11',
    name: 'Kinea II Real Estate Equity',
    serie: 'Incorporação Residencial',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNRI11',
    name: 'Kinea Renda Imobiliária',
    serie: 'Híbrido',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNSC11',
    name: 'Kinea Securities',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'KNUQ11',
    name: 'Kinea Unique HY CDI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'LASC11',
    name: 'Legatus Shoppings',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'LATR11B',
    name: 'Lateres',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'LAVF11',
    name: 'Lavoura',
    serie: 'Híbrido',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'LFTT11',
    name: 'Loft II',
    serie: 'Incorporação Residencial',
    adminitrator: 'MAF',
  },
  {
    ticker: 'LGCP11',
    name: 'Log CP Inter',
    serie: 'Logisticos',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'LIFE11',
    name: 'Life Capital',
    serie: 'Outros',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'LKDV11',
    name: 'Development V1',
    serie: 'Híbrido',
    adminitrator: null,
  },
  {
    ticker: 'LLAO11',
    name: 'BS2 Allinvestments',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'LOFT11B',
    name: 'Loft I (Cota Sênior)',
    serie: 'Incorporação Residencial',
    adminitrator: 'MAF',
  },
  {
    ticker: 'LOFT13B',
    name: 'Loft I (Cota Subordinada)',
    serie: 'Incorporação Residencial',
    adminitrator: 'MAF',
  },
  {
    ticker: 'LPLP11',
    name: 'Lago da Pedra',
    serie: 'Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'LRDI11',
    name: 'Leblon Realty Desenvolvimento I',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'LSAG11',
    name: 'Leste Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'LSPA11',
    name: 'Leste Riva Equity Preferencial I',
    serie: 'Incorporação Residencial',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'LUGG11',
    name: 'Luggo',
    serie: 'Residencial',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'LVBI11',
    name: 'VBI Logístico',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MADS11',
    name: 'Mauá Capital Desenvolvimento I',
    serie: 'Incorporação',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MALL11',
    name: 'Genial Malls',
    serie: 'Shopping/Varejo',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'MANA11',
    name: 'Manatí Capital Hedge Fund',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'MATV11',
    name: 'More Gestão Ativa de Recebíveis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'MAVC11',
    name: 'MAV Crédito Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'MAXR11',
    name: 'Max Retail',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MCCI11',
    name: 'Mauá Capital Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MCHF11',
    name: 'Mauá Capital Hedge Fund',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MCHY11',
    name: 'Mauá High Yield',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MFAI11',
    name: 'Mérito Fundos e Ações Imobiliárias',
    serie: 'Fundo de Fundos',
    adminitrator: 'MÉRITO',
  },
  {
    ticker: 'MFCR11',
    name: 'Merito Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'MÉRITO',
  },
  {
    ticker: 'MFII11',
    name: 'Mérito Desenvolvimento Imobiliário I',
    serie: 'Incorporação Residencial',
    adminitrator: 'MÉRITO',
  },
  {
    ticker: 'MGCR11',
    name: 'Mogno CRIs Multiestratégia',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MGFF11',
    name: 'Mogno Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MGHT11',
    name: 'Mogno Hoteis',
    serie: 'Hoteis',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MGIM11',
    name: 'Mogno Real Estate Impact Development',
    serie: 'Híbrido',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'MGRI11',
    name: 'Mogno Properties',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'MINT11',
    name: 'Mint Educacional',
    serie: 'Educacional',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MMPD11',
    name: 'Mauá Capital MPD Desenvolvimento Residencial',
    serie: 'Outros',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MMVE11',
    name: 'Maresias',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'MOFF11',
    name: 'Multioffices 2',
    serie: 'Lajes Comerciais',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'MORC11',
    name: 'More Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MORE11',
    name: 'More Real Estate FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MSHP11',
    name: 'Mais Shopping Largo 13',
    serie: 'Shopping/Varejo',
    adminitrator: 'BEM DTVM',
  },
  {
    ticker: 'MTOF11',
    name: 'Alianza Multioffices',
    serie: 'Híbrido',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'MTRS11',
    name: 'Metropolis',
    serie: 'Outros',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MVFI11',
    name: 'MV9 FII',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MXRF11',
    name: 'Maxi Renda',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'MYDW11',
    name: 'Riza Meyenii',
    serie: 'Híbrido',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'NAVT11',
    name: 'Navi Imobiliário Total Return',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'NCHB11',
    name: 'NCH Brasil Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'NCRA11',
    name: 'NCH Recebíveis do Agronegócio Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'NCRI11',
    name: 'Navi Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'NEWL11',
    name: 'Newport Logística',
    serie: 'Logisticos',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'NEWU11',
    name: 'Newport Renda Urbana',
    serie: 'Lajes Comerciais',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'NPAR11',
    name: 'Nestpar',
    serie: 'Incorporação',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'NSLU11',
    name: 'Hospital Nossa Senhora de Lourdes',
    serie: 'Hospital',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'NVHO11',
    name: 'Novo Horizonte',
    serie: 'Hospital',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'NVIF11B',
    name: 'Nova I',
    serie: 'Híbrido',
    adminitrator: 'MAF',
  },
  {
    ticker: 'OCRE11',
    name: 'Octo FII',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.',
  },
  {
    ticker: 'OGHY11',
    name: 'Órama High Yield',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'OGIN11',
    name: 'Órama FIC-INFRA',
    serie: 'N/D',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'OIAG11',
    name: 'Ourinvest Innovation Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'ONEF11',
    name: 'The One',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'OPTM11',
    name: 'Patrimonial IV',
    serie: 'Híbrido',
    adminitrator: 'FRAM Capital',
  },
  {
    ticker: 'ORPD11',
    name: 'Ouro Verde Desenvolvimento Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'TRUSTEE DTVM',
  },
  {
    ticker: 'OUFF11',
    name: 'Ourinvest Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BANCO OURINVEST S.A.',
  },
  {
    ticker: 'OUJP11',
    name: 'Ourinvest JPP',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'FINAXIS CORRETORA',
  },
  {
    ticker: 'OULG11',
    name: 'Ourinvest Logística',
    serie: 'Logisticos',
    adminitrator: 'BANCO OURINVEST S.A.',
  },
  {
    ticker: 'OURE11',
    name: 'Ourinvest Renda Estruturada',
    serie: 'Híbrido',
    adminitrator: 'BANCO OURINVEST S.A.',
  },
  {
    ticker: 'PABY11',
    name: 'Panamby',
    serie: 'Incorporação',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'PATB11',
    name: 'Pateo Bandeirantes',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'PATC11',
    name: 'Pátria Edifícios Corporativos',
    serie: 'Lajes Comerciais',
    adminitrator: 'MAF',
  },
  {
    ticker: 'PATL11',
    name: 'Pátria Logística',
    serie: 'Logisticos',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'PBLV11',
    name: 'Prologis Brazil Logistics Venture',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PBYR11',
    name: 'Panamby Renda Master',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'PCAS11',
    name: 'Praia do Castelo',
    serie: 'Outros',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'PEMA11',
    name: 'Performa Real Estate',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PLCA11',
    name: 'Plural BRB Crédito Agro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'PLCR11',
    name: 'Plural Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'PLRI11',
    name: 'Polo',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'PNCR11',
    name: 'Panorama Crédito Residencial',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PNDL11',
    name: 'Panorama Desenvolvimento Logístico',
    serie: 'Incorporação',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PNLM11',
    name: 'Panorama Last Mile SBC',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PNPR11',
    name: 'Panorama Properties',
    serie: 'Incorporação',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'PNRC11',
    name: 'Panorama Real Estate Crédito',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'PORD11',
    name: 'Polo Crédito Imobiliário',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'PQAG11',
    name: 'Parque Anhanguera',
    serie: 'Logisticos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'PQDP11',
    name: 'Parque Dom Pedro Shopping Center',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'PRSN11B',
    name: 'Personale I',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'PRSV11',
    name: 'Presidente Vargas',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'PRTS11',
    name: 'Multi Properties',
    serie: 'Shopping/Varejo',
    adminitrator: 'MAF',
  },
  {
    ticker: 'PRZS11',
    name: 'Prazo',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'PURB11',
    name: 'Plural Renda Urbana',
    serie: 'Híbrido',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'PVBI11',
    name: 'VBI Prime Properties',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'QAGR11',
    name: 'Quasar Agro',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'QAMI11',
    name: 'Quasar Crédito',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'QIRI11',
    name: 'Quatá Imob Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBAG11',
    name: 'RB Capital Agre',
    serie: 'Incorporação Residencial',
    adminitrator: 'CITIBANK DTVM',
  },
  {
    ticker: 'RBBV11',
    name: 'JHSF Rio Bravo Fazenda Boa Vista',
    serie: 'Incorporação',
    adminitrator: 'CAIXA ECONOMICA FEDERAL',
  },
  {
    ticker: 'RBCB11',
    name: 'Rio Bravo Crédito Imobiliário I',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBDS11',
    name: 'RB Capital Desenvolvimento Residencial II',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RBED11',
    name: 'Rio Bravo Renda Educacional',
    serie: 'Educacional',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBFF11',
    name: 'Rio Bravo Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBGS11',
    name: 'RB Capital General Shopping Sulacap',
    serie: 'Shopping/Varejo',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RBHG11',
    name: 'Rio Bravo Crédito Imobiliário High Grade',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBHY11',
    name: 'Rio Bravo Crédito Imobiliário High Yield',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBIF11',
    name: 'Rio Bravo ESG FIC FI FI-Infra',
    serie: 'N/D',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'RBIR11',
    name: 'RB Capital Desenvolvimento Residencial IV',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RBLG11',
    name: 'RB Capital Logístico',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBOP11',
    name: 'Rio Bravo Oportunidades Imobiliárias',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBPD11',
    name: 'RB Capital Prime Realty II',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'CITIBANK DTVM',
  },
  {
    ticker: 'RBPR11',
    name: 'RB Capital Prime Realty I',
    serie: 'Incorporação Residencial',
    adminitrator: 'CITIBANK DTVM',
  },
  {
    ticker: 'RBRD11',
    name: 'RB Capital Renda II',
    serie: 'Híbrido',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'RBRF11',
    name: 'RBR Alpha Multiestratégia Real Estate',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBRI11',
    name: 'RBR Desenvolvimento III',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBRL11',
    name: 'RBR Log',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBRM11',
    name: 'RBR Desenvolvimento',
    serie: 'Incorporação',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBRP11',
    name: 'RBR Properties FII',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBRR11',
    name: 'RBR Rendimentos High Grade',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBRS11',
    name: 'Rio Bravo Renda Residencial',
    serie: 'Residencial',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBRU11',
    name: 'RB Capital Renda Urbana',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RBRX11',
    name: 'RBR Plus Multiestratégia Real Estate',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBRY11',
    name: 'RBR Crédito Imobiliário Estruturado',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RBTS11',
    name: 'RB Capital TFO Situs',
    serie: 'Incorporação',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RBVA11',
    name: 'Rio Bravo Renda Varejo',
    serie: 'Híbrido',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RBVO11',
    name: 'Rio Bravo Crédito Imobiliário II',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RCCS11',
    name: 'REP 1 CCS',
    serie: 'Shopping/Varejo',
    adminitrator: 'CREDIT SUISSE',
  },
  {
    ticker: 'RCFA11',
    name: 'Grupo RCFA',
    serie: 'Incorporação',
    adminitrator: 'TERRA',
  },
  {
    ticker: 'RCFF11',
    name: 'RBR Desenvolvimento Comercial Feeder FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RCKF11',
    name: 'Rock FII',
    serie: 'N/D',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RCRB11',
    name: 'Rio Bravo Renda Corporativa',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'RCRI11B',
    name: 'RB Capital Rendimentos',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RDPD11',
    name: 'V2 Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RECR11',
    name: 'REC Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RECT11',
    name: 'REC Renda Imobiliária',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RECX11',
    name: 'REC Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'REIT11',
    name: 'Singulare FII',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'RELG11',
    name: 'REC Logística',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'REON11',
    name: 'Residenciais One',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RFOF11',
    name: 'RB Capital I Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RINV11',
    name: 'Real Investor FII',
    serie: 'Híbrido',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'RMAI11',
    name: 'REAG Multi Ativos Imobiliários',
    serie: 'Híbrido',
    adminitrator: 'REAG',
  },
  {
    ticker: 'RNDP11',
    name: 'Fundo BB Renda de Papéis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'RNGO11',
    name: 'Rio Negro',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'ROOF11',
    name: 'Rooftop I',
    serie: 'Incorporação Residencial',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'RPRI11',
    name: 'RBR Premium Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'RRCI11',
    name: 'RB Capital Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RSBU11B',
    name: 'RSB 1',
    serie: 'Híbrido',
    adminitrator: 'NSG CAPITAL DTVM',
  },
  {
    ticker: 'RSPD11',
    name: 'RB Capital Desenvolvimento Residencial III',
    serie: 'Incorporação Residencial',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'RURA11',
    name: 'Itaú Asset Rural Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'RURD11',
    name: 'Itaú Asset Rural Dólar Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'RVBI11',
    name: 'VBI Reits FOF',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'RZAG11',
    name: 'Riza Agro Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'RZAK11',
    name: 'Riza Akin',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RZAT11',
    name: 'Riza Arctium Real Estate',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'RZEO11',
    name: 'Riza Eos Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'RZTR11',
    name: 'Riza Terrax',
    serie: 'Agronegócio',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'SAAG11',
    name: 'Santander Agências',
    serie: 'Agencias Bancárias',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'SACL11',
    name: 'São Carlos Renda Imobiliária',
    serie: 'N/D',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'SADI11',
    name: 'Santander Papéis Imobiliários CDI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'SANTANDER CACEIS',
  },
  {
    ticker: 'SAIC11B',
    name: 'SIA Corporate',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRB DTVM',
  },
  {
    ticker: 'SALI11',
    name: 'Vênus',
    serie: 'Outros',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'SARE11',
    name: 'Santander Renda de Aluguéis',
    serie: 'Híbrido',
    adminitrator: 'SANTANDER SECURITIES',
  },
  {
    ticker: 'SBCL11',
    name: 'FRAM Capital SBCLog',
    serie: 'Logisticos',
    adminitrator: 'FRAM Capital',
  },
  {
    ticker: 'SCPF11',
    name: 'SCP',
    serie: 'Shopping/Varejo',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'SDIL11',
    name: 'SDI Rio Bravo Renda Logística',
    serie: 'Logisticos',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'SEED11',
    name: 'Hedge Seed',
    serie: 'Híbrido',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'SEQR11',
    name: 'Sequóia III Renda Imobiliária',
    serie: 'Híbrido',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'SFND11',
    name: 'São Fernando',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'SFRO11',
    name: 'São Francisco 34',
    serie: 'Híbrido',
    adminitrator: 'CM CAPITAL MARKETS',
  },
  {
    ticker: 'SHDP11B',
    name: 'Shopping Parque Dom Pedro',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SHOP11',
    name: 'Multi Shoppings',
    serie: 'Shopping/Varejo',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SHPH11',
    name: 'Shopping Pátio Higienópolis',
    serie: 'Shopping/Varejo',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'SHSO11',
    name: 'SH Special Opps',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'SIGR11',
    name: 'SIG Capital Recebíveis Pulverizados',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SJAU11',
    name: 'SJ AU Logística',
    serie: 'Logisticos',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'SLDZ11',
    name: 'LAV SLDZ Desenvolvimento Imobiliário',
    serie: 'N/D',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'SNAG11',
    name: 'Suno Agro Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'SNCI11',
    name: 'Suno Recebíveis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SNEL11',
    name: 'Suno Energias Limpas FII',
    serie: 'Outros',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'SNFF11',
    name: 'Suno Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SNID11',
    name: 'Suno Infra',
    serie: 'N/D',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SNLG11',
    name: 'Suno Log FII',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'SOLR11',
    name: 'Solarium',
    serie: 'Híbrido',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'SPAF11',
    name: 'Spa',
    serie: 'Shopping/Varejo',
    adminitrator: 'PLURAL',
  },
  {
    ticker: 'SPDE11',
    name: 'WHG Finvest SP Realty',
    serie: 'Residencial',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'SPMO11',
    name: 'Supremo FII',
    serie: 'Híbrido',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'SPTW11',
    name: 'SP Downtown',
    serie: 'Lajes Comerciais',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'SPVJ11',
    name: 'Sucesspar Varejo',
    serie: 'Shopping/Varejo',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'SPXS11',
    name: 'SPX SYN Multiestratégia',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'SRVD11',
    name: 'Serra Verde',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'STFI11',
    name: 'Santander Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'SANTANDER SECURITIES',
  },
  {
    ticker: 'STRX11',
    name: 'StarX',
    serie: 'Shopping/Varejo',
    adminitrator: 'INTER DTVM',
  },
  {
    ticker: 'TBOF11',
    name: 'TB Office',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'TCIN11',
    name: 'G5 Cidade Nova',
    serie: 'Lajes Comerciais',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'TCIN12',
    name: 'G5 Cidade Nova (Cota Ordinária)',
    serie: 'Lajes Comerciais',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'TCPF11',
    name: 'Treecorp Real Estate I',
    serie: 'Incorporação',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'TELD11',
    name: 'Tellus Desenvolvimento Logístico',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'TELF11',
    name: 'Tellus Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'TELM11',
    name: 'Tellus Multiestratégia',
    serie: 'Outros',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'TEPP11',
    name: 'Tellus Properties',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'TFOF11',
    name: 'Hedge TOP FOFII',
    serie: 'Fundo de Fundos',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'TGAR11',
    name: 'TG Ativo Real',
    serie: 'Híbrido',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'THRA11',
    name: 'Cyrela Thera Corporate',
    serie: 'Lajes Comerciais',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'TJKB11',
    name: 'Tjk Renda Imobiliária',
    serie: 'Lajes Comerciais',
    adminitrator: 'BR-CAPITAL',
  },
  {
    ticker: 'TMPS11',
    name: 'Itaú Tempus',
    serie: 'Fundo de Fundos',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'TORD11',
    name: 'Tordesilhas EI',
    serie: 'Híbrido',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'TORM11',
    name: 'Tourmalet I',
    serie: 'Incorporação',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'TOUR11',
    name: 'Tourmalet II',
    serie: 'Incorporação',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'TRNT11',
    name: 'Torre Norte',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'TRXB11',
    name: 'TRX Real Estate II',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'TRXF11',
    name: 'TRX Real Estate',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'TSER11',
    name: 'Tishman Speyer Renda Corporativa',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'TSNC11',
    name: 'Transinc',
    serie: 'Lajes Comerciais',
    adminitrator: 'btg pactual',
  },
  {
    ticker: 'UMED11',
    name: 'Unimed Investcoop Nacional',
    serie: 'Outros',
    adminitrator: 'COINVALORES',
  },
  {
    ticker: 'URPR11',
    name: 'Urca Prime Renda',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'VCJR11',
    name: 'Vectis Juros Real',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'VCRA11',
    name: 'Vectis Datagro Crédito Agronegócio Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'INTRAG',
  },
  {
    ticker: 'VCRI11',
    name: 'Vinci Credit Securities',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VCRR11',
    name: 'Vectis Renda Residencial',
    serie: 'Residencial',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VDSV11',
    name: 'Vic Desenvolvimento Vintage 22/23',
    serie: 'N/D',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'VERE11',
    name: 'Vereda',
    serie: 'Lajes Comerciais',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'VGHF11',
    name: 'Valora Hedge Fund',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO DAYCOVAL',
  },
  {
    ticker: 'VGIA11',
    name: 'Valora CRA Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VGIP11',
    name: 'Valora CRI Índice de Preço',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VGIR11',
    name: 'Valora CRI CDI',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VIDS11',
    name: 'Vic Desenvolvimento - Vintage 20/21',
    serie: 'Incorporação',
    adminitrator: 'BANCO GENIAL',
  },
  {
    ticker: 'VIFI11',
    name: 'Vinci Instrumentos Financeiros',
    serie: 'Fundo de Fundos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VILG11',
    name: 'Vinci Logística',
    serie: 'Logisticos',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VINO11',
    name: 'Vinci Offices',
    serie: 'Lajes Comerciais',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VISC11',
    name: 'Vinci Shopping Centers',
    serie: 'Shopping/Varejo',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VIUR11',
    name: 'Vinci Imóveis Urbanos',
    serie: 'Híbrido',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VJFD11',
    name: 'JFDCAM',
    serie: 'Híbrido',
    adminitrator: 'SINGULARE',
  },
  {
    ticker: 'VLJS11',
    name: 'Vector Queluz Lajes Corporativas',
    serie: 'Lajes Comerciais',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'VLOL11',
    name: 'Vila Olímpia Corporate',
    serie: 'Lajes Comerciais',
    adminitrator: 'OLIVEIRA TRUST',
  },
  {
    ticker: 'VOTS11',
    name: 'Votorantim Securities Master',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'VPSI11',
    name: 'Polo Shopping Indaiatuba',
    serie: 'Shopping/Varejo',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'VRTA11',
    name: 'Fator Verità',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'BANCO FATOR',
  },
  {
    ticker: 'VSEC11',
    name: 'Votorantim Securities',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'VSHO11',
    name: 'Votorantim Shopping',
    serie: 'Shopping/Varejo',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'VSLH11',
    name: 'Versalhes Recebíveis Imobiliários',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'VTLT11',
    name: 'Votorantim Logística',
    serie: 'Logisticos',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'VTPA11',
    name: 'Votorantim Patrimonial V',
    serie: 'Lajes Comerciais',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'VTPL11',
    name: 'FII Plus',
    serie: 'Logisticos',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VTRT11',
    name: 'Votorantim Securities III',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'VTVI11',
    name: 'Parking Partners',
    serie: 'Shopping/Varejo',
    adminitrator: 'VOTORANTIM ASSET',
  },
  {
    ticker: 'VTXI11',
    name: 'Votorantim Patrimonial XII',
    serie: 'Incorporação',
    adminitrator: 'BV DTVM',
  },
  {
    ticker: 'VVCO11',
    name: 'V2 Edifícios Corporativos',
    serie: 'Lajes Comerciais',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VVPR11',
    name: 'V2 Properties',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VVRI11',
    name: 'V2 Renda Imobiliária',
    serie: 'Híbrido',
    adminitrator: 'BTG PACTUAL',
  },
  {
    ticker: 'VXXV11',
    name: 'Genesis Multiestratégia',
    serie: 'Incorporação',
    adminitrator: 'PLANNER',
  },
  {
    ticker: 'WHGR11',
    name: 'WHG Real Estate',
    serie: 'Híbrido',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'WMRB11B',
    name: 'WM RB Capital',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'CITIBANK DTVM',
  },
  {
    ticker: 'WPLZ11',
    name: 'West Plaza',
    serie: 'Shopping/Varejo',
    adminitrator: 'HEDGE INVESTMENTS',
  },
  {
    ticker: 'WSEC11',
    name: 'Warren Securities',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'WARREN',
  },
  {
    ticker: 'WTSP11B',
    name: 'Ourinvest RE I',
    serie: 'Lajes Comerciais',
    adminitrator: 'BANCO OURINVEST S.A.',
  },
  {
    ticker: 'XBXO11',
    name: 'R Cap 1810 Fundo de Fundos',
    serie: 'Fundo de Fundos',
    adminitrator: 'Monetar',
  },
  {
    ticker: 'XPCA11',
    name: 'XP Crédito Agrícola Fiagro',
    serie: 'Agronegócio',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'XPCI11',
    name: 'XP Crédito',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'XPCM11',
    name: 'XP Corporate Macaé',
    serie: 'Lajes Comerciais',
    adminitrator: 'RIO BRAVO',
  },
  {
    ticker: 'XPGA11',
    name: 'XP Recebíveis',
    serie: 'Recebíveis Imobiliários',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'XPHT11',
    name: 'XP Hotéis (Cota Sênior)',
    serie: 'Hoteis',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'XPHT12',
    name: 'XP Hotéis (Cota Ordinária)',
    serie: 'Hoteis',
    adminitrator: 'GENIAL INVESTIMENTOS',
  },
  {
    ticker: 'XPID11',
    name: 'XP FIC FI-Infra',
    serie: 'N/D',
    adminitrator: 'PLURAL',
  },
  {
    ticker: 'XPIN11',
    name: 'XP Industrial',
    serie: 'Logisticos',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'XPLG11',
    name: 'XP Log',
    serie: 'Logisticos',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'XPML11',
    name: 'XP Malls',
    serie: 'Shopping/Varejo',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'XPPR11',
    name: 'XP Properties',
    serie: 'Lajes Comerciais',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'XPSF11',
    name: 'XP Selection',
    serie: 'Fundo de Fundos',
    adminitrator: 'XP INVESTIMENTOS',
  },
  {
    ticker: 'YUFI11',
    name: 'Yuca',
    serie: 'Residencial',
    adminitrator: 'BRL TRUST',
  },
  {
    ticker: 'ZAVI11',
    name: 'Zavit Real Estate Fund',
    serie: 'Híbrido',
    adminitrator: 'VÓRTX',
  },
  {
    ticker: 'ZIFI11',
    name: 'Zion Capital',
    serie: 'Outros',
    adminitrator: 'TRUSTEE DTVM',
  },
]
